spring.application.name=planner-rest
// spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.url=jdbc:postgresql://localhost:5432/planner_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

owner.security.token=OWNER-PLANNER-SECURITY-TOKEN@2024

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=dc0526ab8e493e
spring.mail.password=2e21df2bc51cd3
spring.mail.properties.smtp.smtp.auth=true
spring.mail.properties.smtp.smtp.starttls.enable=true
